command:
  check_backup_encryption:
    title: DHIS2 SA-ID DB-08 | Check if Database Backups are Encrypted
    exec: |
      backup_scripts=$(lxc exec postgres -- crontab -l | awk '{print $NF}')

      for script in $backup_scripts; do
        script_path=$(lxc exec postgres -- which $script)

        # Check if the script exists and examine its contents
        if [ -f "$script_path" ]; then
          backup_path=$(lxc exec postgres -- grep -Eo "backup_path\s*=\s*['\"]?([^'\"]+)" "$script_path" | awk -F= '{print $2}' | tr -d " '\"")
          remote_storage=$(lxc exec postgres -- grep -Eo "remote_storage\s*=\s*['\"]?([^'\"]+)" "$script_path" | awk -F= '{print $2}' | tr -d " '\"")

          # Check if the backup path is local and if it is encrypted
          if [ -n "$backup_path" ]; then
            if [ "$(lxc exec postgres -- test -f "$backup_path" && echo $?)" -eq 0 ] && [[ "$(lxc exec postgres -- stat -c "%a" "$backup_path")" =~ ^(640|660)$ ]]; then
              echo "Local backup file path: $backup_path"

              if lxc exec postgres -- grep -q "openssl.*cipher" "$script_path"; then
                echo "Backups are being encrypted"
              else
                echo "Backups are not being encrypted"
              fi
            else
              echo "Invalid or inaccessible local backup file path: $backup_path"
            fi
          fi

          # Check if the backup path is remote and if encrypted
          if [ -n "$remote_storage" ]; then
            echo "Remote backup storage: $remote_storage"

            # Check if encryption is enabled
            if lxc exec postgres -- grep -q "openssl.*cipher" "$script_path"; then
              echo "Backups are being encrypted"
            else
              echo "Backups are not being encrypted"
            fi
          fi
        fi
      done
    exit-status: 0
    stdout:
      - "/Local backup file path: .*/"
      - "/Remote backup storage: .*/"
      - "Backups are encrypted"
    meta:
      failed: "Database Backups are not being encrypted"
