command:
  check_network_security_monitoring:
    title: DHIS2 SA-ID OS-12 | Check Network-Based Security Monitoring and Alerting
    exec: |
      if pgrep -x "snort" >/dev/null; then
        echo "Snort is running"
        exit 0
      elif pgrep -x "suricata" >/dev/null; then
        echo "Suricata is running"
        exit 0
      elif pgrep -x "fail2ban-server" >/dev/null; then
        echo "Fail2Ban is running"
        exit 0
      else
        echo "No network-based security monitoring and alerting system (Snort, Suricata, Fail2Ban) found"
        exit 1
      fi
    exit-status: 0
    stdout:
      - "/Snort is running/"
      - "/Suricata is running/"
      - "/Fail2Ban is running/"
    meta:
      failed: "No network-based security monitoring and alerting system (Snort, Suricata, Fail2Ban) found"
