command:
  check_offsite_backup:
    title: DHIS2 SA-ID DB-03 | Check if Offsite Backups are taken
    exec: |
      # Search for all scripts in the crontab
      cron_scripts=$(lxc exec postgres -- crontab -l | awk -F ' ' '{print $NF}')

      # Iterate over the scripts and examine their content
      for script in $cron_scripts; do
        script_path=$(lxc exec postgres -- which $script)

        # Confirm the existence of the script and check for common backup tools
        if [ -f "$script_path" ] && lxc exec postgres -- grep -q "rsync" "$script_path"; then
          echo "Offsite backup script found: $script_path"
          exit 0
        fi
      done

      echo "Offsite Backup is not configured"
      exit 1
    exit-status: 0
    stdout:
      - "/Offsite Backup is configured: .*/"
    meta:
      failed: "Offsite Backup is not configured"
