command:
  ssh_permit_root:
    title: DHIS2 SA-ID OS-03 | Check if SSH password authentication is disabled
    exec: grep -Ei "passwordauthentication" /etc/ssh/sshd_config
    exit-status:
      or:
        - 0
        - 1
    stdout:
      - "/^(?i)PasswordAuthentication no/"
      - "!/^(?i)PasswordAuthentication yes/"
    meta:
      failed: "PasswordAuthentication in /etc/ssh/sshd_config is set to yes. It should be set to no"
