command:
  check_dhis_admin_access:
    title: DHIS2 SA-ID AP-01 | Check if DHIS2 admin access is disabled
    exec: |
      container_name=$(lxc list | awk '{print $2}' | grep -E '^(hmis|dhis|tracker)$' | head -1)
      if [ "$container_name" = "hmis" ]; then
        dhis_path="/hmis"
      elif [ "$container_name" = "dhis" ]; then
        dhis_path="/dhis"
      elif [ "$container_name" = "tracker" ]; then
        dhis_path="/tracker"
      else
        echo "Unable to determine DHIS2 container name"
        exit 1
      fi

      domain_name=$(lxc exec proxy -- sh -c 'if [ -f /etc/nginx/conf.d/*.conf ]; then grep -oP "(?<=server_name\s).*(?=;)" /etc/nginx/conf.d/*.conf; elif [ -f /etc/apache2/sites-enabled/apache-dhis2.conf ]; then grep -oP "(?<=ServerName\s).*$" /etc/apache2/sites-enabled/apache-dhis2.conf; fi')

      http_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Host: $domain_name" -d "j_username=admin&j_password=district" "https://$domain_name$dhis_path/dhis-web-commons/security/login.action")
      if [[ $http_response =~ ^30[27]$ ]]; then
        echo "DHIS2 admin access is enabled with default credentials."
        exit 0
      else
        echo "DHIS2 admin access is disabled."
        exit 1
      fi
    exit-status: 0
    meta:
      failed: "DHIS2 admin access is enabled with default credentials."
